"""initial commit

Revision ID: be582912f6b0
Revises: 
Create Date: 2026-03-02 00:36:53.545664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be582912f6b0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('media',
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profession',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tag',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('user',
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=True),
    sa.Column('last_name', sa.String(length=25), nullable=True),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('profession_id', sa.BigInteger(), nullable=True),
    sa.Column('posts_count', sa.BigInteger(), nullable=False),
    sa.Column('posts_read_count', sa.BigInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_email', sa.String(length=255), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['profession_id'], ['profession.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('category_follow',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'category_id', name='uq_category_follow_user_id_category_id')
    )
    op.create_index('ix_category_follow_category_id', 'category_follow', ['category_id'], unique=False)
    op.create_index('ix_category_follow_user_id', 'category_follow', ['user_id'], unique=False)
    op.create_table('moderation_report',
    sa.Column('reporter_user_id', sa.BigInteger(), nullable=False),
    sa.Column('target_type', sa.Enum('POST', 'COMMENT', 'USER', name='moderation_target_type'), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_report_reporter_user_id', 'moderation_report', ['reporter_user_id'], unique=False)
    op.create_index('ix_moderation_report_status', 'moderation_report', ['status'], unique=False)
    op.create_index('ix_moderation_report_target_type_target_id', 'moderation_report', ['target_type', 'target_id'], unique=False)
    op.create_table('notification',
    sa.Column('recipient_user_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.Enum('COMMENT_REPLY', 'COMMENT_ON_POST', 'POST_PUBLISHED', 'POST_APPROVED', 'NEW_FOLLOWER', 'MENTION', 'SYSTEM', name='notification_type'), nullable=False),
    sa.Column('payload', sa.String(length=2000), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notification_actor_user_id', 'notification', ['actor_user_id'], unique=False)
    op.create_index('ix_notification_is_read', 'notification', ['is_read'], unique=False)
    op.create_index('ix_notification_recipient_user_id', 'notification', ['recipient_user_id'], unique=False)
    op.create_index('ix_notification_type', 'notification', ['type'], unique=False)
    op.create_table('post',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('bookmarks_count', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'PUBLISHED', 'SCHEDULED', 'ARCHIVED', name='post_status'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_index('ix_post_category_id', 'post', ['category_id'], unique=False)
    op.create_index('ix_post_published_at', 'post', ['published_at'], unique=False)
    op.create_index('ix_post_status', 'post', ['status'], unique=False)
    op.create_index('ix_post_user_id', 'post', ['user_id'], unique=False)
    op.create_table('tag_follow',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tag_id', name='uq_tag_follow_user_id_tag_id')
    )
    op.create_index('ix_tag_follow_tag_id', 'tag_follow', ['tag_id'], unique=False)
    op.create_index('ix_tag_follow_user_id', 'tag_follow', ['user_id'], unique=False)
    op.create_table('user_follow',
    sa.Column('follower_user_id', sa.BigInteger(), nullable=False),
    sa.Column('followed_user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['followed_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['follower_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_user_id', 'followed_user_id', name='uq_user_follow_follower_followed')
    )
    op.create_index('ix_user_follow_followed_user_id', 'user_follow', ['followed_user_id'], unique=False)
    op.create_index('ix_user_follow_follower_user_id', 'user_follow', ['follower_user_id'], unique=False)
    op.create_table('user_sessions',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_sessions_expires_at', 'user_sessions', ['expires_at'], unique=False)
    op.create_index('ix_user_sessions_user_id', 'user_sessions', ['user_id'], unique=False)
    op.create_table('comment',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('VISIBLE', 'HIDDEN', 'DELETED', name='comment_status'), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_parent_id', 'comment', ['parent_id'], unique=False)
    op.create_index('ix_comment_post_id', 'comment', ['post_id'], unique=False)
    op.create_index('ix_comment_status', 'comment', ['status'], unique=False)
    op.create_index('ix_comment_user_id', 'comment', ['user_id'], unique=False)
    op.create_table('moderation_action',
    sa.Column('report_id', sa.BigInteger(), nullable=False),
    sa.Column('moderator_user_id', sa.BigInteger(), nullable=True),
    sa.Column('action_type', sa.Enum('WARN', 'HIDE', 'DELETE', 'BAN', 'RESTORE', name='moderation_action_type'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['moderator_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['moderation_report.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_moderation_action_moderator_user_id', 'moderation_action', ['moderator_user_id'], unique=False)
    op.create_index('ix_moderation_action_report_id', 'moderation_action', ['report_id'], unique=False)
    op.create_table('post_bookmark',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_bookmark_post_id_user_id')
    )
    op.create_index('ix_post_bookmark_post_id', 'post_bookmark', ['post_id'], unique=False)
    op.create_index('ix_post_bookmark_user_id', 'post_bookmark', ['user_id'], unique=False)
    op.create_table('post_media',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('media_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'media_id', name='uq_post_media_post_id_media_id')
    )
    op.create_index('ix_post_media_media_id', 'post_media', ['media_id'], unique=False)
    op.create_index('ix_post_media_post_id', 'post_media', ['post_id'], unique=False)
    op.create_table('post_revision',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('editor_user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('change_summary', sa.String(), nullable=True),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['editor_user_id'], ['user.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_post_revision_editor_user_id', 'post_revision', ['editor_user_id'], unique=False)
    op.create_index('ix_post_revision_post_id', 'post_revision', ['post_id'], unique=False)
    op.create_table('post_tag',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_post_tag_post_id_tag_id')
    )
    op.create_index('ix_post_tag_post_id', 'post_tag', ['post_id'], unique=False)
    op.create_index('ix_post_tag_tag_id', 'post_tag', ['tag_id'], unique=False)
    op.create_table('post_vote',
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_post_vote_value'),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_vote_post_id_user_id')
    )
    op.create_index('ix_post_vote_post_id', 'post_vote', ['post_id'], unique=False)
    op.create_index('ix_post_vote_user_id', 'post_vote', ['user_id'], unique=False)
    op.create_table('comment_vote',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.SmallInteger(), nullable=False),
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('value IN (-1, 1)', name='ck_comment_vote_value'),
    sa.ForeignKeyConstraint(['comment_id'], ['comment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comment_id', 'user_id', name='uq_comment_vote_comment_id_user_id')
    )
    op.create_index('ix_comment_vote_comment_id', 'comment_vote', ['comment_id'], unique=False)
    op.create_index('ix_comment_vote_user_id', 'comment_vote', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_comment_vote_user_id', table_name='comment_vote')
    op.drop_index('ix_comment_vote_comment_id', table_name='comment_vote')
    op.drop_table('comment_vote')
    op.drop_index('ix_post_vote_user_id', table_name='post_vote')
    op.drop_index('ix_post_vote_post_id', table_name='post_vote')
    op.drop_table('post_vote')
    op.drop_index('ix_post_tag_tag_id', table_name='post_tag')
    op.drop_index('ix_post_tag_post_id', table_name='post_tag')
    op.drop_table('post_tag')
    op.drop_index('ix_post_revision_post_id', table_name='post_revision')
    op.drop_index('ix_post_revision_editor_user_id', table_name='post_revision')
    op.drop_table('post_revision')
    op.drop_index('ix_post_media_post_id', table_name='post_media')
    op.drop_index('ix_post_media_media_id', table_name='post_media')
    op.drop_table('post_media')
    op.drop_index('ix_post_bookmark_user_id', table_name='post_bookmark')
    op.drop_index('ix_post_bookmark_post_id', table_name='post_bookmark')
    op.drop_table('post_bookmark')
    op.drop_index('ix_moderation_action_report_id', table_name='moderation_action')
    op.drop_index('ix_moderation_action_moderator_user_id', table_name='moderation_action')
    op.drop_table('moderation_action')
    op.drop_index('ix_comment_user_id', table_name='comment')
    op.drop_index('ix_comment_status', table_name='comment')
    op.drop_index('ix_comment_post_id', table_name='comment')
    op.drop_index('ix_comment_parent_id', table_name='comment')
    op.drop_table('comment')
    op.drop_index('ix_user_sessions_user_id', table_name='user_sessions')
    op.drop_index('ix_user_sessions_expires_at', table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index('ix_user_follow_follower_user_id', table_name='user_follow')
    op.drop_index('ix_user_follow_followed_user_id', table_name='user_follow')
    op.drop_table('user_follow')
    op.drop_index('ix_tag_follow_user_id', table_name='tag_follow')
    op.drop_index('ix_tag_follow_tag_id', table_name='tag_follow')
    op.drop_table('tag_follow')
    op.drop_index('ix_post_user_id', table_name='post')
    op.drop_index('ix_post_status', table_name='post')
    op.drop_index('ix_post_published_at', table_name='post')
    op.drop_index('ix_post_category_id', table_name='post')
    op.drop_table('post')
    op.drop_index('ix_notification_type', table_name='notification')
    op.drop_index('ix_notification_recipient_user_id', table_name='notification')
    op.drop_index('ix_notification_is_read', table_name='notification')
    op.drop_index('ix_notification_actor_user_id', table_name='notification')
    op.drop_table('notification')
    op.drop_index('ix_moderation_report_target_type_target_id', table_name='moderation_report')
    op.drop_index('ix_moderation_report_status', table_name='moderation_report')
    op.drop_index('ix_moderation_report_reporter_user_id', table_name='moderation_report')
    op.drop_table('moderation_report')
    op.drop_index('ix_category_follow_user_id', table_name='category_follow')
    op.drop_index('ix_category_follow_category_id', table_name='category_follow')
    op.drop_table('category_follow')
    op.drop_table('user')
    op.drop_table('tag')
    op.drop_table('profession')
    op.drop_table('media')
    op.drop_table('category')
    # ### end Alembic commands ###
