const PRODUCT_INFO = {
  name: 'librhub',
  description: 'Generated by create next app',
  logo: '/favicon.png',
  favicon: '/favicon.svg',
  url: 'https://www.shadcnblocks.com',
  contact: {
    phone: '+998901234567',
    email: 'contact@floss.uz',
  },
  terms_of_use: '',
  creator: 'Floss Uzbekistan',
};

export { PRODUCT_INFO };
