# Application configuration

app:
  name: LibrHub
  version: 0.1.0
  
server:
  port: 3000
  host: localhost
  
features:
  darkMode: true
  analytics: false
  
api:
  baseUrl: https://api.example.com
  timeout: 5000
  endpoints:
    - name: books
      path: /books
      methods: [GET, POST]
    - name: authors
      path: /authors
      methods: [GET]
